name: extract
channels:
  - conda-forge
  - nvidia/label/cuda-11.8.0
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cmake=3.27.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgomp=13.1.0
  - libnsl=2.0.0
  - libsqlite=3.42.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.1.1
  - pip=24.3.1
  - python=3.10.12
  - readline=8.2
  - setuptools=68.0.0
  - tk=8.6.12
  - wheel=0.41.0
  - xz=5.2.6
  - pip:
      - absl-py==1.4.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - attrs==23.1.0
      - bddl==1.0.1
      - cachetools==4.2.4
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - click==8.1.6
      - cloudpickle==1.2.2
      - cmake==3.27.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - Cython==0.29.36
      - decorator==4.4.2
      - dill==0.3.7
      - dm-control==1.0.3
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - easydict==1.9
      - egl-probe==1.0.2
      - einops==0.4.1
      - evdev==1.6.1
      - exceptiongroup==1.1.3
      - farama-notifications==0.0.4
      - fasteners==0.18
      - fastjsonschema==2.18.0
      - filelock==3.12.2
      - fonttools==4.41.1
      - fsspec==2023.6.0
      - funcsigs==1.0.2
      - future==0.18.3
      - gitdb==4.0.10
      - gitpython==3.1.32
      - glfw==2.6.2
      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.56.2
      - gym==0.15.4
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - h5py==3.9.0
      - huggingface-hub==0.16.4
      - hydra-core==1.2.0
      - idna==3.4
      - imageio==2.31.1
      - imageio-ffmpeg==0.4.8
      - iniconfig==2.0.0
      - jinja2==3.1.2
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter-core==5.3.1
      - jupytext==1.15.1
      - kiwisolver==1.4.4
      - labmaze==1.0.6
      - lazy-loader==0.3
      - lockfile==0.12.2
      - lit==16.0.6
      - llvmlite==0.40.1
      - lxml==4.9.3
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
        #- metaworld==2.0.0
      - moviepy==1.0.3
        #- mpi4py==3.1.4
      - mpmath==1.3.0
      - mujoco==2.3.7
        #- mujoco-py==2.0.2.5
      - numpy==1.21.6
      - multiprocess==0.70.15
      - nbformat==5.9.2
      - networkx==3.1
      - numba==0.57.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.6.0.66
      - packaging==23.1
      - pandas==2.0.3
      - pathos==0.3.1
      - pathtools==0.1.2
      - pillow==10.0.0
      - platformdirs==3.10.0
      - pluggy==1.2.0
      - pox==0.3.3
      - ppft==1.7.6.7
      - proglog==0.1.10
      - protobuf==3.20.0
      - psutil==5.9.5
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pyglet==1.3.2
      - pynput==1.7.6
      - pyopengl==3.1.7
      - pyparsing==2.4.7
      - pytest==7.4.0
      - python-dateutil==2.8.2
      - python-xlib==0.33
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - referencing==0.30.2
      - regex==2023.8.8
      - requests==2.31.0
      - requests-oauthlib==1.3.1
        #- rlkit==0.2.1.dev0
        #- robomimic==0.2.0
        #- robosuite==1.4.1
      - rpds-py==0.10.0
      - rsa==4.9
      - scikit-image==0.21.0
      - scipy==1.11.1
      - seaborn==0.12.2
      - sentry-sdk==1.28.1
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - sympy==1.12
      - tensorboard==2.1.1
      - tensorboardx==2.0
      - termcolor==2.3.0
      - thop==0.1.1-2209072238
      - tifffile==2023.7.18
      - tokenizers==0.12.1
      - toml==0.10.2
      - tomli==2.0.1
      - torch==2.0.1
      - torchvision==0.15.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - transformers==4.21.1
      - triton==2.0.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - urllib3==2.0.4
      - wandb==0.15.8
      - werkzeug==2.3.6
